name: Build and Release Samurai Kernel

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update && sudo apt install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev fakeroot bc wget tar liblz4-tool lz4 xz-utils gh debhelper libdw-dev elfutils

      - name: Clone kernel mainline source
        run: |
          git clone --depth=1 --branch v${{ vars.KERNEL_VERSION }} \
            https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git \
            linux

      - name: Build samurai kernel
        working-directory: linux
        run: |
          cp ../config .config
          fakeroot make -j$(nproc) deb-pkg LOCALVERSION=-samurai

      - name: Collect .deb files
        run: |
          ls -la
          mv linux-image-*.deb samurai-${{vars.KERNEL_VERSION}}-amd64.deb
          mv linux-headers-*.deb samurai-headers-${{vars.KERNEL_VERSION}}-amd64.deb
          mv linux-libc-dev*.deb samurai-libc-dev-${{vars.KERNEL_VERSION}}-amd64.deb
          ls -la
          mkdir -p artifacts
          mv *.deb artifacts/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in artifacts/*.deb; do
            gh release upload ${{ github.ref_name }} "$file" --clobber
          done
